version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd extension
  build:
    commands:
      - mkdir build
      - cd chrome
      - zip -r ../build/chrome.zip .
      - cp ../firefox/manifest.json manifest.json
      - zip -r ../build/firefox.zip .
      - cd ..
  post_build:
    commands:
      - aws s3 sync ./build $BUCKET/extension/latest