version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd extension
  build:
    commands:
      - mkdir build
      - cd chrome
      - zip -r ../build/chrome.zip .
      - cp ../firefox/manifest.json manifest.json # only the manifest file is different on firefox
      - zip -r ../build/firefox.zip .
      - cd ..
  post_build:
    commands:
      - aws s3 sync ./build $BUCKET/extension/latest
      - |
          if expr "$ENV" : "PROD"; then
            aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths "/extension/latest*"
          fi