version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd site
      - npm ci
      - sudo adduser notroot
  build:
    run-as: notroot
    commands:
      - npm run build
  post_build:
    commands:
      - echo "post build"
