version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd site
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./build $BUCKET
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT --paths "/*"
