version: 0.1
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - cd site
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "post build"
